### ISSUE TITLE
I have noticed a few typos 

### ISSUE THREAD

**Issue by ghmorrison** [sylvaticus/SPMLJ#5]
Sorry I thought I had to create an issue before I made changes. I will try to figure it out how to do a pull request and send you some corrections.

**Comment by sylvaticus** [comment]
Thank you,!

Basically, either you manually fork the github repository, clone it, do your modifications, commit, push back to github and open a pull request or you edit directly in the github source file and the steps above are done or suggested automatically...

**Comment by ghmorrison** [comment]
Thanks your response it was very helpful.

**Comment by sylvaticus** [comment]
I have merged your pull request, thanks again...

**Comment by ghmorrison** [comment]
I am trying to get the course to run on my computer. Should it be possible
with Julia 1.10.3 and could you tell me where the instructions are?

**Comment by sylvaticus** [comment]
Just clone the git repository. For the quizzes working locally you need to build the documentation to create HTML pages out of the course, just run the script to make the documentation (makedoc.jl, either include it or run it with julia makedoc.jl)... I am on a mobile, I can reply to you with more detailed instructions on Monday...

**Comment by ghmorrison** [comment]
Thank you for the quick reply.

I will try it and let you know.

George
